#the worst ever password gen place
def badgen(n) :
  passwordString = "wergotjepirgjeaprgiejpirsgjsqrgiuoehrjgoiwejgrpiowjserpgoiwjerpgiojweproigjweproigjpweoirgjpweoirgjpwioerjgpiowejrgpiowerjgpwioerjgpiowerjgpiowerjgpiowerjgpwioejrgpoeiwjrgpioewjrgpiowejrgpioewrjgpoeiwrjgpwoierjgpowierjgpweirjgwergotjepirgjeaprgiejpirsgjsqrgiuoehrjgoiwejgrpiowjserpgoiwjerpgiojweproigjweproigjpweoirgjpweoirgjpwioerjgpiowejrgpiowerjgpwioerjgpiowerjgpiowerjgpiowerjgpwioejrgpoeiwjrgpioewjrgpiowejrgpioewrjgpoeiwrjgpwoierjgpowierjgpweirjgwergotjepirgjeaprgiejpirsgjsqrgiuoehrjgoiwejgrpiowjserpgoiwjerpgiojweproigjweproigjpweoirgjpweoirgjpwioerjgpiowejrgpiowerjgpwioerjgpiowerjgpiowerjgpiowerjgpwioejrgpoeiwjrgpioewjrgpiowejrgpioewrjgpoeiwrjgpwoierjgpowierjgpweirjgwergotjepirgjeaprgiejpirsgjsqrgiuoehrjgoiwejgrpiowjserpgoiwjerpgiojweproigjweproigjpweoirgjpweoirgjpwioerjgpiowejrgpiowerjgpwioerjgpiowerjgpiowerjgpiowerjgpwioejrgpoeiwjrgpioewjrgpiowejrgpioewrjgpoeiwrjgpwoierjgpowierjgpweirjgwergotjepirgjeaprgiejpirsgjsqrgiuoehrjgoiwejgrpiowjserpgoiwjerpgiojweproigjweproigjpweoirgjpweoirgjpwioerjgpiowejrgpiowerjgpwioerjgpiowerjgpiowerjgpiowerjgpwioejrgpoeiwjrgpioewjrgpiowejrgpioewrjgpoeiwrjgpwoierjgpowierjgpweirjgwergotjepirgjeaprgiejpirsgjsqrgiuoehrjgoiwejgrpiowjserpgoiwjerpgiojweproigjweproigjpweoirgjpweoirgjpwioerjgpiowejrgpiowerjgpwioerjgpiowerjgpiowerjgpiowerjgpwioejrgpoeiwjrgpioewjrgpiowejrgpioewrjgpoeiwrjgpwoierjgpowierjgpweirjg"
  password = passwordString[0:n]
  print("your password is: "+ passwordString)
forced = input("give number for pwLength:   ")

forced = int(forced)
badgen(forced)
